@extends('layouts.app')

@section('title', 'Pedidos recebidos')

@section('content')
<div class="container py-5" style="max-width:1080px">
    <div class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4"><div><div class="eyebrow mb-2">Painel do vendedor</div><h1 class="h2 fw-bold mb-1">Pedidos recebidos</h1><p class="text-secondary mb-0">Atualize a preparação e a entrega depois do pagamento confirmado.</p></div><a class="btn btn-outline-violet" href="{{ route('seller.products.index') }}">Meus itens</a></div>
    @if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
    @forelse($orders as $order)
        @php($items = $order->product ? collect([$order->product]) : $order->cart?->items?->pluck('product')->filter() ?? collect())
        <article class="card border-0 shadow-sm rounded-4 p-4 mb-3"><div class="row g-4"><div class="col-lg-5"><div class="small text-secondary">Pedido #{{ $order->id }} · {{ $order->paid_at?->format('d/m/Y H:i') ?? 'Pagamento confirmado' }}</div><h2 class="h6 fw-bold mt-2 mb-2">{{ $items->pluck('name')->implode(', ') ?: 'Itens da sacola' }}</h2><div class="fw-bold">R$ {{ number_format((float) $order->amount, 2, ',', '.') }}</div><hr><div class="small"><strong>{{ $order->customer_name }}</strong><br>{{ $order->customer_phone }} · {{ $order->customer_email }}<br>CEP {{ $order->customer_postal_code }}, nº {{ $order->customer_address_number }} {{ $order->customer_address_complement }}</div></div><div class="col-lg-7"><form method="POST" action="{{ route('seller.orders.update', $order) }}" class="row g-2">@csrf @method('PUT')<div class="col-md-6"><label class="form-label small" for="fulfillment_{{ $order->id }}">Etapa</label><select id="fulfillment_{{ $order->id }}" name="fulfillment_status" class="form-select">@foreach(['payment_received' => 'Pagamento recebido', 'separating' => 'Separando', 'packing' => 'Embalando', 'shipped' => 'Enviado', 'completed' => 'Concluído'] as $value => $label)<option value="{{ $value }}" @selected(($order->fulfillment_status ?? 'payment_received') === $value)>{{ $label }}</option>@endforeach</select></div><div class="col-md-6"><label class="form-label small" for="delivery_{{ $order->id }}">Entrega</label><select id="delivery_{{ $order->id }}" name="delivery_method" class="form-select"><option value="">A definir</option><option value="pickup" @selected($order->delivery_method === 'pickup')>Retirada</option><option value="delivery" @selected($order->delivery_method === 'delivery')>Entrega local</option><option value="shipping" @selected($order->delivery_method === 'shipping')>Envio</option></select></div><div class="col-md-6"><label class="form-label small" for="tracking_{{ $order->id }}">Código de rastreio</label><input id="tracking_{{ $order->id }}" class="form-control" name="tracking_code" value="{{ $order->tracking_code }}"></div><div class="col-md-6"><label class="form-label small" for="note_{{ $order->id }}">Observação</label><input id="note_{{ $order->id }}" class="form-control" name="seller_note" value="{{ $order->seller_note }}"></div><div class="col-12"><button class="btn btn-violet">Salvar atualização</button></div></form></div></div></article>
    @empty
        <div class="card border-0 shadow-sm rounded-4 p-5 text-center"><h2 class="h4">Nenhum pedido confirmado ainda.</h2><p class="text-secondary mb-0">Quando um pagamento for recebido, ele aparecerá aqui.</p></div>
    @endforelse
    <div class="mt-4">@include('components.pagination-controls', ['paginator' => $orders])</div>
</div>
@endsection
