@extends('layouts.app')

@section('title', 'Configurações do vendedor')

@section('content')
<div class="container py-5" style="max-width: 900px">
    <div class="mb-4"><div class="eyebrow mb-2">{{ $isPreview ? 'Prévia administrativa' : 'Painel do vendedor' }}</div><h1 class="h2 fw-bold mb-2">Configurações da conta</h1><p class="text-secondary">As credenciais ficam criptografadas e não são exibidas depois de salvas.</p></div>
    @if($isPreview)<div class="alert alert-info">Você está vendo a prévia do painel de vendedor. O link público aparece apenas para contas cadastradas como vendedor.</div>@else<div class="row g-3 mb-4"><div class="col-sm-6"><div class="card border-0 shadow-sm rounded-4 p-3"><div class="small text-secondary">Itens publicados</div><div class="h3 fw-bold mb-0">{{ $productsCount }}</div><a class="small" href="{{ route('seller.products.index') }}">Gerenciar itens</a></div></div><div class="col-sm-6"><div class="card border-0 shadow-sm rounded-4 p-3"><div class="small text-secondary">Vendas recebidas</div><div class="h3 fw-bold mb-0">{{ $salesCount }}</div><a class="small" href="{{ route('seller.orders.index') }}">Acompanhar pedidos</a></div></div></div>@endif
    @if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
    @if($shareUrl)<div class="card border-0 shadow-sm rounded-4 p-4 mb-4"><h2 class="h5 fw-bold">Seu link público</h2><p class="text-secondary small">Compartilhe este endereço no WhatsApp, Instagram ou onde quiser para mostrar seus itens disponíveis.</p><div class="input-group"><input class="form-control" value="{{ $shareUrl }}" readonly><button type="button" class="btn btn-outline-violet" data-copy-link="{{ $shareUrl }}">Copiar</button></div><div class="d-flex flex-wrap gap-2 mt-3"><button type="button" class="btn btn-violet" data-share-link="{{ $shareUrl }}">Compartilhar catálogo</button><a class="btn btn-outline-violet" href="{{ $shareUrl }}" target="_blank">Ver meu catálogo</a></div></div>@endif
    <form method="POST" action="{{ route('seller.settings.update') }}" class="card border-0 shadow-sm rounded-4 p-4">
        @csrf @method('PUT')
        <h2 class="h5 fw-bold">Asaas</h2><p class="small text-secondary">Use as credenciais da sua própria conta Asaas. Campos vazios mantêm a informação já salva.</p>
        <div class="row g-3 mb-4"><div class="col-md-6"><label class="form-label" for="asaas_api_key">Chave da API @if($settings?->asaas_api_key)<span class="badge text-bg-success">Configurada</span>@endif</label><input class="form-control" id="asaas_api_key" name="asaas_api_key" type="password" autocomplete="new-password" placeholder="{{ $settings?->asaas_api_key ? 'Deixe vazio para manter' : '' }}">@error('asaas_api_key')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div><div class="col-md-6"><label class="form-label" for="asaas_webhook_token">Token do webhook @if($settings?->asaas_webhook_token)<span class="badge text-bg-success">Configurado</span>@endif</label><input class="form-control" id="asaas_webhook_token" name="asaas_webhook_token" type="password" autocomplete="new-password" placeholder="{{ $settings?->asaas_webhook_token ? 'Deixe vazio para manter' : '' }}">@error('asaas_webhook_token')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div></div>
        <h2 class="h5 fw-bold">Telegram</h2><div class="row g-3 mb-4"><div class="col-md-7"><label class="form-label" for="telegram_bot_token">Token do bot @if($settings?->telegram_bot_token)<span class="badge text-bg-success">Configurado</span>@endif</label><input class="form-control" id="telegram_bot_token" name="telegram_bot_token" type="password" autocomplete="new-password" placeholder="{{ $settings?->telegram_bot_token ? 'Deixe vazio para manter' : '' }}">@error('telegram_bot_token')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div><div class="col-md-5"><label class="form-label" for="telegram_chat_id">Chat ID @if($settings?->telegram_chat_id)<span class="badge text-bg-success">Configurado</span>@endif</label><input class="form-control" id="telegram_chat_id" name="telegram_chat_id" type="text" placeholder="{{ $settings?->telegram_chat_id ? 'Deixe vazio para manter' : '' }}">@error('telegram_chat_id')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div></div>
        <h2 class="h5 fw-bold">Shopee</h2><div class="row g-3 mb-4"><div class="col-md-4"><label class="form-label" for="shopee_partner_id">Partner ID</label><input class="form-control" id="shopee_partner_id" name="shopee_partner_id" type="text">@error('shopee_partner_id')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div><div class="col-md-4"><label class="form-label" for="shopee_partner_key">Partner key</label><input class="form-control" id="shopee_partner_key" name="shopee_partner_key" type="password" autocomplete="new-password">@error('shopee_partner_key')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div><div class="col-md-4"><label class="form-label" for="shopee_shop_id">Shop ID</label><input class="form-control" id="shopee_shop_id" name="shopee_shop_id" type="text">@error('shopee_shop_id')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div></div>
        <button class="btn btn-violet">Salvar configurações</button>
    </form>
</div>
@endsection

@push('scripts')<script>document.querySelector('[data-copy-link]')?.addEventListener('click', async (event) => { await navigator.clipboard.writeText(event.currentTarget.dataset.copyLink); event.currentTarget.textContent = 'Copiado'; }); document.querySelector('[data-share-link]')?.addEventListener('click', async (event) => { const url = event.currentTarget.dataset.shareLink; if (navigator.share) { await navigator.share({ title: 'Meu catálogo no Desapega.ghotme', text: 'Veja os itens que estou vendendo!', url }); } else { await navigator.clipboard.writeText(url); event.currentTarget.textContent = 'Link copiado'; } });</script>@endpush
