@php($bundle = $bundle ?? null)
<div class="row g-3">
    <div class="col-md-8"><label class="form-label">Nome do combo</label><input name="name" class="form-control" value="{{ old('name', $bundle?->name) }}" required></div>
    <div class="col-md-4"><label class="form-label">Preço no Pix</label><input name="pix_price" type="number" step="0.01" min="0" class="form-control" value="{{ old('pix_price', $bundle?->pix_price) }}" required></div>
    <div class="col-md-8"><label class="form-label">Foto de capa</label><input name="cover_image" type="file" class="form-control" accept="image/*"></div>
    <div class="col-md-4 d-flex align-items-end"><div class="form-check mb-2"><input class="form-check-input" type="checkbox" name="active" value="1" id="active" @checked(old('active', $bundle?->active ?? true))><label class="form-check-label" for="active">Combo ativo</label></div></div>
    <div class="col-12"><label class="form-label">Descrição</label><textarea name="description" rows="3" class="form-control">{{ old('description', $bundle?->description) }}</textarea></div>
    <div class="col-12"><label class="form-label">Itens do combo</label><p class="small text-secondary">Selecione pelo menos dois itens. Se um deles for vendido, o combo fica indisponível automaticamente.</p><div class="row g-2">@forelse($products as $product)@php($checked = in_array($product->id, old('products', $bundle?->products?->pluck('id')->all() ?? [])))<div class="col-md-6"><label class="border rounded-3 p-3 w-100 d-flex gap-2 align-items-start"><input class="form-check-input mt-1" type="checkbox" name="products[]" value="{{ $product->id }}" @checked($checked)><span><strong>{{ $product->name }}</strong><br><small class="text-secondary">R$ {{ number_format($product->pix_price, 2, ',', '.') }} · {{ $product->status_label }}</small></span></label></div>@empty<div class="col-12"><div class="alert alert-warning mb-0">Cadastre ao menos dois itens antes de criar um combo.</div></div>@endforelse</div></div>
</div>
@if($errors->any())<div class="alert alert-danger mt-3"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="mt-4 d-flex gap-2"><button class="btn btn-violet" @disabled($products->count() < 2)>Salvar combo</button><a href="{{ route('seller.bundles.index') }}" class="btn btn-outline-secondary">Cancelar</a></div>
